version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 9999:5432

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/todoapp/:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend


volumes:
  postgres_data:
